alias bd := build-debug
alias br := build-release
alias c := clean
alias d := doc
alias t := test

build-debug:
    cargo build
    mv target/debug/qcs-bins qcs

build-release:
    cargo build --release
    mv target/release/qcs-bins qcs

clean:
    rm -i ./qcs

doc:
    cargo doc

test:
    cargo nextest run && cargo test --doc
