[package]
name = "qcs-circuit-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qcs-core = { path = "../qcs-core" }
logos = "0.14.0"
nom = "7.1.3"
oq3_semantics = "0.5.0"
thiserror = "1.0.58"
